/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_bugke_com_ndkdemo_NDKDemo */

#ifndef _Included_www_bugke_com_ndkdemo_NDKDemo
#define _Included_www_bugke_com_ndkdemo_NDKDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_bugke_com_ndkdemo_NDKDemo
 * Method:    getNDKDemoText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_bugke_com_ndkdemo_NDKDemo_getNDKDemoText
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
